image: node:latest

before_script:
# install ssh-agent
- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
# run ssh-agent
- eval $(ssh-agent -s)
# add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
- ssh-add <(echo "$SSH_PRIVATE_KEY")
- mkdir -p ~/.ssh
# - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


variables:
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"

stages:
  - test
  - deploy to staging

test:
  stage: test
  services:
    - redis:latest
    - postgres:latest
  before_script:
    - cp config/config.sample.js config/config.js
    - cp config/knexfile.sample.js knexfile.js
    - apt-get update
    - apt-get install -y postgresql-client
    - npm i -g yarn
  script:
    - yarn
    - yarn build
    - yarn test
    - yarn report

staging:
  stage: deploy to staging
  before_script:
    - npm install pm2 -g
  script:
    - chmod 700 $HOME/.ssh
    - ssh-keyscan -H 'staging.debtcollective.org' >> $HOME/.ssh/known_hosts
    - ssh-keyscan -H 'gitlab.com' >> $HOME/.ssh/known_hosts
    - pm2 deploy ecosystem.json staging
  environment: staging
  except:
    - master
  dependencies:
    - test
