# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

before_script:
  - cp config/config.sample.js config/config.js
  - cp config/knexfile.sample.js knexfile.js
  - apt-get install postgresql

services:
  - redis:latest
  - postgres:latest

stages:
  - test

test:
  stage: test
  script:
    - psql -h "postgres" -U "postgres" -c 'DROP DATABASE IF EXISTS "debtcollective_test;"'
    - psql -h "postgres" -U "postgres" -c 'CREATE DATABASE "debtcollective_test"'
    - npm install
    - npm test
    - npm run report
