cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - deploy

test:
  retry:
    max: 2
  image: debtcollective/dispute-tools-test:latest
  stage: test
  services:
    - postgres:10
    - redis:4
  variables:
    POSTGRES_DB: dispute_tools_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ''
    DB_HOST: postgres
    DB_USER: postgres
    REDIS_HOST: redis
  before_script:
    - cp config/config.sample.js config/config.js
    - cp config/knexfile.sample.js knexfile.js
    - yarn install
    - yarn build
  script:
    - yarn report

build:
  retry:
    max: 1
  image: docker:stable
  stage: build
  variables:
  before_script:
    - docker login -u $CI_REGISTRY_USER -u $CI_REGISTRY_PASSWORD
  script:
    - make build

deploy:
  retry:
    max: 1
  image: docker:dind
  stage: deploy
  variables:
  before_script:
    - docker login -u $CI_REGISTRY_USER -u $CI_REGISTRY_PASSWORD
  script:
    - make push
  only:
    - master
