image: node:latest

variables:
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"

stages:
  - test
  - deploy to staging

test:
  stage: test
  services:
    - redis:latest
    - postgres:latest
  before_script:
    - cp config/config.sample.js config/config.js
    - cp config/knexfile.sample.js knexfile.js
    - apt-get update
    - apt-get install -y postgresql-client
  script:
    - npm install --silent
    - npm run build
    - npm test
    - npm run report

staging:
  stage: deploy to staging
  script:
    - npm install pm2 -g
    - mkdir $HOME/.ssh
    - chmod 700 $HOME/.ssh
    - ssh-keyscan -H '54.160.57.68' >> $HOME/.ssh/known_hosts
    - pm2 deploy ecosystem.json staging
  environment: staging
  except:
    - master
  dependencies:
    - test
