version: 2

defaults: &defaults
  working_directory: ~/tdc-dispute-tools
  docker:
    - image: circleci/node:8.11.4-stretch
    - image: circleci/postgres:9.6.2-alpine
    - image: circleci/redis:3-alpine

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: bash scripts/copy_config
      - run: yarn build
      - persist_to_workspace:
          root: ~/tdc-dispute-tools
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tdc-dispute-tools
      - run: sudo apt-get update
      - run: sudo apt-get install pdftk postgresql-client
      - run: sudo bash ./scripts/install_ghostscript_debian
      - run: yarn test
      - run: yarn report

  deploy_development:
    <<: *defaults
    requires: build
    steps:
      - attach_workspace:
          at: ~/tdc-dispute-tools
      - setup_remote_docker
      - run: bash ./scripts/deploy_development

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - master
      - hold:
          type: approval
          filters:
            branches:
              only:
                - development
                - master
      - deploy_development:
          requires:
            - build
            - hold
          filters:
            branches:
              only:
                - development
      - deploy_production:
          requires:
            - build
            - hold
          filters:
            branches:
              only:
                - master
