version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
      # Dependencies
      - image: postgres:9.6.2

    working_directory: ~/tdc-dispute-tools

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: bash scripts/copy_config
      - run: yarn build

  test:
    docker:
      - image: circleci/node:8.9.1
      # Dependencies
      - image: postgres:9.6.2
    requires: build
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install pdftk postgresql-client
      - run: yarn test
      - run: yarn report

  deploy:
    docker:
      - image: circleci/node:8.9.1
      # Dependencies
      - image: postgres:9.6.2
    requires: build
    steps:
      - run: echo "Deployment not yet implemented"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
